// flow-typed signature: 9a1878ed5d329208d8e17036cd18f563
// flow-typed version: <<STUB>>/babel-require_v^1.0.1/flow_v0.101.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-require/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-require/dist/main.js' {
  declare module.exports: $Exports<'babel-require/dist/main'>;
}
