// flow-typed signature: db16bebe33a1f1107e29f118716f4bd6
// flow-typed version: <<STUB>>/fixed-data-table-2_v^0.8.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixed-data-table-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixed-data-table-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fixed-data-table-2/dist/fixed-data-table' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/dist/fixed-data-table.min' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ColumnGroupsExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ContextExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ExpandedExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/FilterExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/FlexGrowExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/helpers/cells' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/helpers/ExampleImage' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/helpers/examplePropTypes' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/helpers/FakeObjectDataListStore' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/helpers/HOC' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/HideColumnExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ObjectDataExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/PaginationExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ReorderExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ResizeExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ResponsiveExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ScrollToColumnExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/ScrollToRowExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/SortExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/StylingExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/TooltipExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/examples/TouchScrollExample' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ActionTypes' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/BrowserSupportCore' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/camelize' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/cancelAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/clamp' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/columnActions' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/columnStateHelper' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/columnTemplates' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/columnWidths' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/computeRenderedRows' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/convertColumnElementsToData' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/cssVar' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/cx' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/debounceCore' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/DOMMouseMoveTracker' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/emptyFunction' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/EventListener' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTable' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableBufferedRows' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableCell' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableCellDefault' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableCellGroup' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableColumn' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableColumnGroup' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableColumnReorderHandle' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableColumnResizeHandle' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableContainer' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableHelper' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableRoot' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableRow' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableRowBuffer' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableScrollHelper' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableStore' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableTranslateDOMPosition' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/FixedDataTableWidthHelper' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/getVendorPrefixedName' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/Heap' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/IntegerBufferSet' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/invariant' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/isEventSupported' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/joinClasses' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/Keys' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/Locale' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/nativeRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/normalizeWheel' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/Object.assign' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/PrefixIntervalTree' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/React' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ReactDOM' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ReactTouchHandler' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/ReactWheelHandler' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/reducers' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/requestAnimationFramePolyfill' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/roughHeights' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/scrollActions' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/scrollAnchor' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/Scrollbar' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/scrollbarsVisible' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/shallowEqual' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/shallowEqualSelector' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/tableHeights' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/translateDOMPositionXY' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/updateRowHeight' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/UserAgent_DEPRECATED' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/internal/widthHelper' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/main' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/testRunner' {
  declare module.exports: any;
}

declare module 'fixed-data-table-2/webpack.config-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fixed-data-table-2/dist/fixed-data-table.js' {
  declare module.exports: $Exports<'fixed-data-table-2/dist/fixed-data-table'>;
}
declare module 'fixed-data-table-2/dist/fixed-data-table.min.js' {
  declare module.exports: $Exports<'fixed-data-table-2/dist/fixed-data-table.min'>;
}
declare module 'fixed-data-table-2/examples/ColumnGroupsExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ColumnGroupsExample'>;
}
declare module 'fixed-data-table-2/examples/ContextExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ContextExample'>;
}
declare module 'fixed-data-table-2/examples/ExpandedExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ExpandedExample'>;
}
declare module 'fixed-data-table-2/examples/FilterExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/FilterExample'>;
}
declare module 'fixed-data-table-2/examples/FlexGrowExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/FlexGrowExample'>;
}
declare module 'fixed-data-table-2/examples/helpers/cells.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/helpers/cells'>;
}
declare module 'fixed-data-table-2/examples/helpers/ExampleImage.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/helpers/ExampleImage'>;
}
declare module 'fixed-data-table-2/examples/helpers/examplePropTypes.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/helpers/examplePropTypes'>;
}
declare module 'fixed-data-table-2/examples/helpers/FakeObjectDataListStore.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/helpers/FakeObjectDataListStore'>;
}
declare module 'fixed-data-table-2/examples/helpers/HOC.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/helpers/HOC'>;
}
declare module 'fixed-data-table-2/examples/HideColumnExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/HideColumnExample'>;
}
declare module 'fixed-data-table-2/examples/ObjectDataExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ObjectDataExample'>;
}
declare module 'fixed-data-table-2/examples/PaginationExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/PaginationExample'>;
}
declare module 'fixed-data-table-2/examples/ReorderExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ReorderExample'>;
}
declare module 'fixed-data-table-2/examples/ResizeExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ResizeExample'>;
}
declare module 'fixed-data-table-2/examples/ResponsiveExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ResponsiveExample'>;
}
declare module 'fixed-data-table-2/examples/ScrollToColumnExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ScrollToColumnExample'>;
}
declare module 'fixed-data-table-2/examples/ScrollToRowExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/ScrollToRowExample'>;
}
declare module 'fixed-data-table-2/examples/SortExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/SortExample'>;
}
declare module 'fixed-data-table-2/examples/StylingExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/StylingExample'>;
}
declare module 'fixed-data-table-2/examples/TooltipExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/TooltipExample'>;
}
declare module 'fixed-data-table-2/examples/TouchScrollExample.js' {
  declare module.exports: $Exports<'fixed-data-table-2/examples/TouchScrollExample'>;
}
declare module 'fixed-data-table-2/internal/ActionTypes.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ActionTypes'>;
}
declare module 'fixed-data-table-2/internal/BrowserSupportCore.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/BrowserSupportCore'>;
}
declare module 'fixed-data-table-2/internal/camelize.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/camelize'>;
}
declare module 'fixed-data-table-2/internal/cancelAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/cancelAnimationFramePolyfill'>;
}
declare module 'fixed-data-table-2/internal/clamp.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/clamp'>;
}
declare module 'fixed-data-table-2/internal/columnActions.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/columnActions'>;
}
declare module 'fixed-data-table-2/internal/columnStateHelper.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/columnStateHelper'>;
}
declare module 'fixed-data-table-2/internal/columnTemplates.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/columnTemplates'>;
}
declare module 'fixed-data-table-2/internal/columnWidths.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/columnWidths'>;
}
declare module 'fixed-data-table-2/internal/computeRenderedRows.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/computeRenderedRows'>;
}
declare module 'fixed-data-table-2/internal/convertColumnElementsToData.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/convertColumnElementsToData'>;
}
declare module 'fixed-data-table-2/internal/cssVar.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/cssVar'>;
}
declare module 'fixed-data-table-2/internal/cx.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/cx'>;
}
declare module 'fixed-data-table-2/internal/debounceCore.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/debounceCore'>;
}
declare module 'fixed-data-table-2/internal/DOMMouseMoveTracker.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/DOMMouseMoveTracker'>;
}
declare module 'fixed-data-table-2/internal/emptyFunction.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/emptyFunction'>;
}
declare module 'fixed-data-table-2/internal/EventListener.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/EventListener'>;
}
declare module 'fixed-data-table-2/internal/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ExecutionEnvironment'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTable.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTable'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableBufferedRows.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableBufferedRows'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableCell.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableCell'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableCellDefault.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableCellDefault'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableCellGroup.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableCellGroup'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableColumn.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableColumn'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableColumnGroup.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableColumnGroup'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableColumnReorderHandle.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableColumnReorderHandle'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableColumnResizeHandle.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableColumnResizeHandle'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableContainer.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableContainer'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableHelper.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableHelper'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableRoot.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableRoot'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableRow.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableRow'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableRowBuffer.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableRowBuffer'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableScrollHelper.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableScrollHelper'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableStore.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableStore'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableTranslateDOMPosition.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableTranslateDOMPosition'>;
}
declare module 'fixed-data-table-2/internal/FixedDataTableWidthHelper.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/FixedDataTableWidthHelper'>;
}
declare module 'fixed-data-table-2/internal/getVendorPrefixedName.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/getVendorPrefixedName'>;
}
declare module 'fixed-data-table-2/internal/Heap.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/Heap'>;
}
declare module 'fixed-data-table-2/internal/IntegerBufferSet.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/IntegerBufferSet'>;
}
declare module 'fixed-data-table-2/internal/invariant.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/invariant'>;
}
declare module 'fixed-data-table-2/internal/isEventSupported.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/isEventSupported'>;
}
declare module 'fixed-data-table-2/internal/joinClasses.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/joinClasses'>;
}
declare module 'fixed-data-table-2/internal/Keys.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/Keys'>;
}
declare module 'fixed-data-table-2/internal/Locale.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/Locale'>;
}
declare module 'fixed-data-table-2/internal/nativeRequestAnimationFrame.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/nativeRequestAnimationFrame'>;
}
declare module 'fixed-data-table-2/internal/normalizeWheel.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/normalizeWheel'>;
}
declare module 'fixed-data-table-2/internal/Object.assign.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/Object.assign'>;
}
declare module 'fixed-data-table-2/internal/PrefixIntervalTree.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/PrefixIntervalTree'>;
}
declare module 'fixed-data-table-2/internal/React.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/React'>;
}
declare module 'fixed-data-table-2/internal/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ReactComponentWithPureRenderMixin'>;
}
declare module 'fixed-data-table-2/internal/ReactDOM.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ReactDOM'>;
}
declare module 'fixed-data-table-2/internal/ReactTouchHandler.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ReactTouchHandler'>;
}
declare module 'fixed-data-table-2/internal/ReactWheelHandler.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/ReactWheelHandler'>;
}
declare module 'fixed-data-table-2/internal/reducers.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/reducers'>;
}
declare module 'fixed-data-table-2/internal/requestAnimationFramePolyfill.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/requestAnimationFramePolyfill'>;
}
declare module 'fixed-data-table-2/internal/roughHeights.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/roughHeights'>;
}
declare module 'fixed-data-table-2/internal/scrollActions.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/scrollActions'>;
}
declare module 'fixed-data-table-2/internal/scrollAnchor.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/scrollAnchor'>;
}
declare module 'fixed-data-table-2/internal/Scrollbar.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/Scrollbar'>;
}
declare module 'fixed-data-table-2/internal/scrollbarsVisible.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/scrollbarsVisible'>;
}
declare module 'fixed-data-table-2/internal/shallowEqual.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/shallowEqual'>;
}
declare module 'fixed-data-table-2/internal/shallowEqualSelector.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/shallowEqualSelector'>;
}
declare module 'fixed-data-table-2/internal/tableHeights.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/tableHeights'>;
}
declare module 'fixed-data-table-2/internal/translateDOMPositionXY.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/translateDOMPositionXY'>;
}
declare module 'fixed-data-table-2/internal/updateRowHeight.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/updateRowHeight'>;
}
declare module 'fixed-data-table-2/internal/UserAgent_DEPRECATED.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/UserAgent_DEPRECATED'>;
}
declare module 'fixed-data-table-2/internal/widthHelper.js' {
  declare module.exports: $Exports<'fixed-data-table-2/internal/widthHelper'>;
}
declare module 'fixed-data-table-2/main.js' {
  declare module.exports: $Exports<'fixed-data-table-2/main'>;
}
declare module 'fixed-data-table-2/testRunner.js' {
  declare module.exports: $Exports<'fixed-data-table-2/testRunner'>;
}
declare module 'fixed-data-table-2/webpack.config-test.js' {
  declare module.exports: $Exports<'fixed-data-table-2/webpack.config-test'>;
}
